# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/justmock"

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock, docs-watcher/*, api/*]
navigation:
## List your directory names and order here, like this:
    getting-started:
        title: Getting Started
        position: 1
    getting-started/api-basics:
        title: JustMock API Basics
        position: 4
    basic-usage:
        title: Basic Mocking
        position: 3
    basic-usage/mock-behaviors:
        title: Mock Behaviors
        position: 2
    basic-usage/mock:
        title: Mock
        position: 3
    advanced-usage:
        title: Advanced Usage
        position: 4
    scenarios:
        title: Scenarios
        position: 6
    integration:
        title: Integrations
        position: 7
    integration/continuous-integration:
        title: Continuous Integration
        position: 3    
    integration/continuous-integration/tfs-azure:
        title: TFS and Azure Pipelines
        position: 1
    integration/code-coverage:
        title: Code Coverage
        position: 4
    knowledge-base:
        title: Knowledge Base
        position: 8       

        
## The application virtual path
baseurl: /devtools/justmock

## Enable CTA Panel
has_cta_panels: true

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "justmock"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

product: "Telerik JustMock"
productName: "Telerik JustMock"
platform: justmock
api_reference_url: "api/"


ff-sheet-id: f22ac032-a3ef-411e-af2e-6202e27709be

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:bmvql-x1xsw'
gcs_api_key: 'AIzaSyC8edQ_EPDSw2G4lsc7HhAfJ6e-aWhQ4bY'

edit_repo_url: https://github.com/telerik/justmock-docs/edit/master

download: http://www.telerik.com/download-trial-file/v2/justmock
nav:
  "Videos": http://www.telerik.com/videos/justmock/work-less-do-more-with-justmock-
  "Release History": https://www.telerik.com/support/whats-new/justmock/release-history
  "About": http://www.telerik.com/products/mocking
  "Pricing": http://www.telerik.com/purchase/individual-justmock

footer:
-
  title: "Getting Started"
  links:
    "Unit Testing and Mocking Explained": https://www.telerik.com/products/mocking/unit-testing.aspx
    "Videos": https://www.telerik.com/videos/justmock
    "FAQs": https://www.telerik.com/products/mocking/faq.aspx
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/justmock
    "Blogs": https://www.telerik.com/blogs/tag/justmock
    "Feedback Portal": https://feedback.telerik.com/Project/105
  
footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
